version: '3.7'


services:
  db:
    environment:
      POSTGRES_MULTIPLE_DATABASES: example_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: fostgres
    image: jhnnsrs/daten:next
    labels:
      - "arkitekt.default.service=db"
  example:
    build: .
    ports:
    - 8888:80
    labels:
      - "arkitekt.default.service=example"
      - "traefik.enable=true"
      - "traefik.http.routers.example.entrypoints=examplesecure"
      - "traefik.http.routers.example.rule=Host(`jhnnsrs-server.hyena-sole.ts.net`)"
      - "traefik.http.services.example.loadbalancer.server.port=80"
      - "traefik.http.routers.example.tls.certresolver=myresolver"
  redis:
    image: redis:latest
    labels:
      - "arkitekt.default.service=redis"
